<?php
/**
 * Customizer Defaults.
 *
 * @package Springoo
 * @author  Springoo
 */

if ( ! defined( 'ABSPATH' ) ) {
	header( 'Status: 403 Forbidden' );
	header( 'HTTP/1.1 403 Forbidden' );
	die();
}

// phpcs:disable WordPress.NamingConventions.PrefixAllGlobals.NonPrefixedVariableFound,WPThemeReview.CoreFunctionality.PrefixAllGlobals.NonPrefixedVariableFound

// Get Sidebar.
$sidebar_list           = [ 'default' => __( 'Default', 'springoo' ) ];
$springoo_get_sidebars  = wp_get_sidebars_widgets();
$springoo_get_sidebars  = array_slice( $springoo_get_sidebars, 1 );
$springoo_grid_list     = [
	1  => __( 'Grid Column 1', 'springoo' ),
	2  => __( 'Grid Column 2', 'springoo' ),
	3  => __( 'Grid Column 3', 'springoo' ),
	4  => __( 'Grid Column 4', 'springoo' ),
	5  => __( 'Grid Column 5', 'springoo' ),
	6  => __( 'Grid Column 6', 'springoo' ),
	7  => __( 'Grid Column 7', 'springoo' ),
	8  => __( 'Grid Column 8', 'springoo' ),
	9  => __( 'Grid Column 9', 'springoo' ),
	10 => __( 'Grid Column 10', 'springoo' ),
	11 => __( 'Grid Column 11', 'springoo' ),
	12 => __( 'Grid Column 12', 'springoo' ),
];
$springoo_sidebar_pos   = [
	'left'  => __( 'Left', 'springoo' ),
	'right' => __( 'Right', 'springoo' ),
	'none'  => __( 'None', 'springoo' ),
];
$springoo_yes_no        = [
	1 => __( 'Yes', 'springoo' ),
	0 => __( 'No', 'springoo' ),
];
$springoo_blog_style    = [
	'normal' => __( 'Normal', 'springoo' ),
	'medium' => __( 'Medium', 'springoo' ),
	'grid'   => __( 'Grid', 'springoo' ),
];
$springoo_search_style  = [
	'normal' => __( 'Normal', 'springoo' ),
	'medium' => __( 'Medium', 'springoo' ),
	'grid'   => __( 'Grid', 'springoo' ),
];
$springoo_content_align = [
	'left'   => __( 'Left', 'springoo' ),
	'center' => __( 'Center', 'springoo' ),
	'right'  => __( 'Right', 'springoo' ),
];

foreach ( $springoo_get_sidebars as $key => $sidebar ) {
	$str   = str_replace( '-', ' ', $key );
	$value = ucwords( $str );
	// Add to the list.
	$sidebar_list[ $key ] = $value;
}

$social_profiles = [
	[
		'label' => 'Facebook',
		'url'   => 'https://www.facebook.com/pixelaarllc/',
		'icon'  => 'si si-thin-facebook',
	],
	[
		'label' => 'Twitter',
		'url'   => '#',
		'icon'  => 'si si-thin-twitter',
	],
	[
		'label' => 'Youtube',
		'url'   => 'https://www.youtube.com/',
		'icon'  => 'si si-bold-youtube',
	],
];

// Default Options.
$springoo_defaults = [
	'blogname'                                          => __( 'Springoo Demo', 'springoo' ),
	'title_tagline_hide_title'                          => 0,
	'title_tagline_hide_tagline'                        => 0,
	'sticky_label'                                      => __( 'Featured', 'springoo' ),
	's_config_lazyload_enable'                          => '1',

	'preload_enable'                                    => 0,
	'preload_animation_type'                            => 'pulse',
	'preload_animation_speed'                           => 'slow',
	'preload_text_enable'                               => 1,
	'preload_text'                                      => 'loading',
	'preload_text_size'                                 => 36,
	'preload_img_enable'                                => 0,
	'preload_img_size'                                  => 100,

	'social_profiles'                                   => $social_profiles,
	'layout_global_site'                                => 'wide',
	'layout_global_content_layout'                      => 'container',
	'layout_global_content_layout_max_width'            => '',
	'layout_global_content_grid'                        => 9,
	'layout_global_sidebar_grid'                        => 3,
	//top header
	'layout_header_top'                                 => 1,
	'layout_header_top_discount'                        => __( 'Free shipping worldwide. Orders over $200', 'springoo' ),
	'layout_header_top_email'                           => __( 'mail@test.com', 'springoo' ),
	//main header
	'layout_header_mobile_backdrop_bg'                  => 1,
	'layout_header_sticky'                              => 0,
	'layout_header_mini_search'                         => 1,
	'layout_header_wishlist'                            => 1,
	'layout_header_login_user_icon'                     => 1,
	'layout_header_show_mini_cart'                      => 1,
	//bottom header
	'layout_header_menu_mobileshow'                     => 'md',
	'layout_header_mobile_menu_style'                   => 'off-canvas-full-mobile-menu',
	'layout_header_menu_alignment'                      => 'right',
	'layout_header_menu_style'                          => 'menu-text',
	'layout_header_menu_hover_style'                    => 'menu-hover-primary',
	'layout_header_submenu_alignment'                   => 'left',
	'layout_header_submenu_width'                       => 280,
	'layout_header_submenu_top_padding'                 => 10,
	'layout_header_submenu_bottom_padding'              => 10,
	'layout_header_submenu_left_padding'                => 20,
	'layout_header_submenu_right_padding'               => 20,
	'layout_header_menu_left_padding'                   => 15,
	'layout_header_menu_right_padding'                  => 15,
	'layout_header_mega_menu_bottom_spacing'            => 12,
	'layout_transparent_header_top_margin'              => 0,
	'layout_footer_widget_column'                       => 4,
	'layout_footer_social'                              => 1,
	'layout_footer_main_top_padding'                    => 70,
	'layout_footer_main_bottom_padding'                 => 70,
	'layout_footer_bottom_top_padding'                  => 20,
	'layout_footer_bottom_bottom_padding'               => 20,
	'layout_footer_apple_store_link'                    => __( '#', 'springoo' ),
	'layout_footer_google_play_store_link'              => __( '#', 'springoo' ),
	'layout_footer_credits_top_padding'                 => 20,
	'layout_footer_credits_bottom_padding'              => 20,
	'layout_footer_scroll_to_top'                       => 1,
	'layout_footer_footer_text'                         => '',
	'layout_footer_newsletter'                          => '',

	//404 page Layout
	'layout_404_image'                                  => SPRINGOO_THEME_URI . 'assets/dist/images/404.svg',
	'layout_404_page_title'                             => __( 'Sorry! The page you requested was not found.', 'springoo' ),
	'layout_404_page_description'                       => __( 'The page you are trying to access doesn\'t exist or has been moved. Try going back to our homepage.', 'springoo' ),
	'layout_404_page_button_text'                       => __( 'Take me home', 'springoo' ),
	'layout_404_page_button_link'                       => __( '#', 'springoo' ),

	'layout_blog_home_category'                         => 1,
	'layout_blog_home_date'                             => 1,
	'layout_blog_home_date_format'                      => 'l j, Y',
	'layout_blog_home_sticky_post'                      => 1,
	'layout_blog_home_sticky_posts_per_page'            => 3,
	'layout_blog_home_post_tab'                         => 0,
	'layout_blog_home_post_tab_posts_per_page'          => 5,
	'layout_blog_home_latest_posts_title'               => __( 'Latest Posts', 'springoo' ),
	'layout_blog_home_latest_posts_column'              => 3,
	'layout_blog_home_latest_posts_thumbnail_position'  => 'default',
	'layout_blog_home_latest_posts_per_page'            => 6,
	'layout_blog_home_latest_posts_excerpt_length'      => 10,

	'layout_blog_sidebar'                               => 'right',
	'layout_blog_style'                                 => 'normal',
	'layout_blog_title-bar'                             => 1,
	'layout_blog_meta'                                  => '',
	'layout_blog_meta-cats'                             => 1,
	'layout_blog_meta-tags'                             => 1,
	'layout_blog_excerpt_length'                        => 50,
	'layout_blog_normal_image'                          => '1400,700',
	'layout_blog_medium_image'                          => '277,395',
	'layout_blog_grid_image'                            => '400,320',
	'layout_blog_grid_column'                           => 2,
	'layout_archive_sidebar'                            => 'right',
	'layout_archive_style'                              => 'normal',
	'layout_archive_title-bar'                          => 1,
	'layout_archive_meta'                               => '',

	//'layout_archive_meta-cats'                 => 1, @TODO tobe removed
	'layout_archive_meta-tags'                          => 1,
	'layout_search_sidebar'                             => 'right',
	'layout_search_style'                               => 'grid',
	'layout_search_title-bar'                           => 1,
	'layout_search_meta'                                => '',
	'layout_search_meta-cats'                           => 1,
	'layout_search_meta-tags'                           => 1,
	'layout_post_sidebar'                               => 'right',
	'layout_post_title-bar'                             => 1,
	'layout_post_title'                                 => 1,
	'layout_post_ft-img-hide'                           => 0,
	'layout_post_ft-img-enlarge'                        => 1,
	'layout_post_content_align'                         => '',
	'layout_show_related_post'                          => 1,
	'layout_related_post_number'                        => 6,
	'layout_related_post_column'                        => 2,
	'layout_enable_related_post_slider'                 => 1,
	'layout_related_post_slider_enable_arrow'           => 1,
	'layout_related_post_slider_enable_dots'            => 1,
	'layout_related_post_slider_enable_autoplay'        => 1,
	'layout_post_meta'                                  => '',
	'layout_post_meta-cats'                             => 1,
	'layout_post_meta-tags'                             => 1,
	'layout_page_sidebar'                               => 'none',
	'layout_page_title-bar'                             => 1,
	'layout_page_title'                                 => 0,
	'layout_page_ft-img-hide'                           => 0,
	'layout_page_ft-img-enlarge'                        => 1,
	'layout_page_content_align'                         => '',

	'colors_global_accent'                              => '', // '#2626f3',
	'colors_global_accent_shade'                        => '', // '#0000f2',
	'colors_global_alt'                                 => '', // '#FFFFFF',
	'colors_global_alt_text'                            => '', // '#333333',
	'colors_global_border'                              => '', // '#e5e5e5',
	'colors_global_heading'                             => '', // '#222222',
	'colors_global_text'                                => '', // '#333333',
	'colors_global_site_bg'                             => '', // '#dddddd',
	'colors_global_content_bg'                          => '', // '#f9f9f9',
	'colors_global_sticky_bg'                           => '', // '#edf2ef',
	'colors_header_bg'                                  => '', // '#FFFFFF',
	'colors_header_border'                              => '', // '#e0e0e0',


	'colors_header2_bg'                                 => '', // '#2626f3',
	'colors_header2_text'                               => '', // '#FFFFFF',
	'colors_header2_sc_si'                              => '', // '#FFFFFF',
	'colors_header2_sc_si_hover'                        => '', // '#FFFFFF',
	'colors_header2_sc_si_hover_bg'                     => '', // '#000000',

	'colors_menu_text'                                  => '', // '#757575',
	'colors_menu_hover'                                 => '', // '#0000f2',
	'colors_menu_sub_text'                              => '', // '#FFFFFF',
	'colors_menu_sub_hover'                             => '', // '#bfbfbf',
	'colors_menu_sub_hover_bg'                          => '', // '#1515b7',
	'colors_menu_sub_bg'                                => '', // '#2626f3',
	'colors_menu_sub_border'                            => '', // '#1919e1',
	'colors_menu_color'                                 => '', // '#FFFFFF',

	'colors_menu_mob_bg'                                => '', // '#2626f3',
	'colors_menu_mob_hover'                             => '', // '#bfbfbf',
	'colors_menu_mob_hover_bg'                          => '', // '#1515b7',
	'colors_menu_mob_border'                            => '', // '#969696',

	'colors_title_bg'                                   => '', // '#f5f5f5',
	'colors_title_text'                                 => '', // '#333333',
	'colors_footer_bg'                                  => '', // '#FFFFFF',
	'colors_footer_heading'                             => '', // '#FFFFFF',
	'colors_footer_text'                                => '', // '#777777',
	'colors_footer_link'                                => '', // '#757575',
	'colors_footer_link_hover'                          => '', // '#2626f3',
	'colors_footer_top_border'                          => '', // '#c1c1c1',
	'colors_footer_border'                              => '', // '#c1c1c1',
	'colors_footer_sc_set_bg'                           => '', // '#DEE1E7',
	'colors_footer_sc_bg'                               => '', // '#FFFFFF',
	'colors_footer_sc_text'                             => '', // '#777777',
	'colors_footer_sc_link'                             => '', // '#353535',
	'colors_footer_sc_link_hover'                       => '', // '#2626f3',
	'colors_footer_sc_si_bg'                            => '', // '#2626f3',
	'colors_footer_sc_si'                               => '', // '#959ca0',
	'colors_footer_sc_si_hover'                         => '', // '#FFFFFF',
	'colors_footer_sc_si_hover_bg'                      => '', // '#0000f2',

	'colors_footer_top_icon'                            => '',
	'colors_footer_top_title'                           => '',
	'colors_footer_top_desc'                            => '',
	'typography_options_subsets'                        => [ 'latin' ],
	'typography_global_scale'                           => 1.125,
	'typography_global_font_family'                     => 'Outfit',
	'typography_global_font_variant'                    => 'default',
	'typography_global_font_size'                       => 16,
	'typography_global_line_height'                     => 1.6,
	'typography_global_text_transform'                  => '',
	'typography_global_letter_spacing'                  => '',
	'typography_global_word_spacing'                    => '',
	'typography_heading_font_family'                    => 'Outfit',
	'typography_heading_font_variant'                   => 'default',
	'typography_heading_font_size'                      => '',
	'typography_heading_line_height'                    => 1.2,
	'typography_heading_text_transform'                 => '',
	'typography_heading_letter_spacing'                 => '',
	'typography_heading_word_spacing'                   => '',
	'typography_heading_h1_font_family'                 => '',
	'typography_heading_h1_font_variant'                => 800,
	'typography_heading_h1_font_size'                   => 50,
	'typography_heading_h1_line_height'                 => '',
	'typography_heading_h1_text_transform'              => '',
	'typography_heading_h1_letter_spacing'              => '',
	'typography_heading_h1_word_spacing'                => '',
	'typography_heading_h2_font_family'                 => '',
	'typography_heading_h2_font_variant'                => 700,
	'typography_heading_h2_font_size'                   => 40,
	'typography_heading_h2_line_height'                 => '',
	'typography_heading_h2_text_transform'              => '',
	'typography_heading_h2_letter_spacing'              => '',
	'typography_heading_h2_word_spacing'                => '',
	'typography_heading_h3_font_family'                 => '',
	'typography_heading_h3_font_variant'                => 600,
	'typography_heading_h3_font_size'                   => 36,
	'typography_heading_h3_line_height'                 => '',
	'typography_heading_h3_text_transform'              => '',
	'typography_heading_h3_letter_spacing'              => '',
	'typography_heading_h3_word_spacing'                => '',
	'typography_heading_h4_font_family'                 => '',
	'typography_heading_h4_font_variant'                => 600,
	'typography_heading_h4_font_size'                   => 28,
	'typography_heading_h4_line_height'                 => '',
	'typography_heading_h4_text_transform'              => '',
	'typography_heading_h4_letter_spacing'              => '',
	'typography_heading_h4_word_spacing'                => '',
	'typography_heading_h5_font_family'                 => '',
	'typography_heading_h5_font_variant'                => 600,
	'typography_heading_h5_font_size'                   => 20,
	'typography_heading_h5_line_height'                 => '',
	'typography_heading_h5_text_transform'              => '',
	'typography_heading_h5_letter_spacing'              => '',
	'typography_heading_h5_word_spacing'                => '',
	'typography_heading_h6_font_family'                 => '',
	'typography_heading_h6_font_variant'                => 600,
	'typography_heading_h6_font_size'                   => 18,
	'typography_heading_h6_line_height'                 => '',
	'typography_heading_h6_text_transform'              => '',
	'typography_heading_h6_letter_spacing'              => '',
	'typography_heading_h6_word_spacing'                => '',
	'typography_menu_font_family'                       => '',
	'typography_menu_font_variant'                      => '500',
	'typography_menu_font_size'                         => '',
	'typography_menu_line_height'                       => false,
	'typography_menu_text_transform'                    => '',
	'typography_menu_letter_spacing'                    => '',
	'typography_menu_word_spacing'                      => '',
	'typography_menu_sub_font_family'                   => '',
	'typography_menu_sub_font_variant'                  => '',
	'typography_menu_sub_font_size'                     => '',
	'typography_menu_sub_line_height'                   => '',
	'typography_menu_sub_text_transform'                => '',
	'typography_menu_sub_letter_spacing'                => '',
	'typography_menu_sub_word_spacing'                  => '',
	'typography_menu_mobile_font_family'                => '',
	'typography_menu_mobile_font_variant'               => '',
	'typography_menu_mobile_font_size'                  => '',
	'typography_menu_mobile_line_height'                => '',
	'typography_menu_mobile_text_transform'             => '',
	'typography_menu_mobile_letter_spacing'             => '',
	'typography_menu_mobile_word_spacing'               => '',
	'typography_site_title_font_family'                 => '',
	'typography_site_title_font_variant'                => '',
	'typography_site_title_font_size'                   => '',
	'typography_site_title_line_height'                 => '',
	'typography_site_title_text_transform'              => '',
	'typography_site_title_letter_spacing'              => '',
	'typography_site_title_word_spacing'                => '',
	'typography_site_tagline_font_family'               => '',
	'typography_site_tagline_font_variant'              => '',
	'typography_site_tagline_font_size'                 => '',
	'typography_site_tagline_line_height'               => '',
	'typography_site_tagline_text_transform'            => '',
	'typography_site_tagline_letter_spacing'            => '',
	'typography_site_tagline_word_spacing'              => '',
	'typography_sidebar_title_font_family'              => '',
	'typography_sidebar_title_font_variant'             => '',
	'typography_sidebar_title_font_size'                => '20',
	'typography_sidebar_title_line_height'              => '',
	'typography_sidebar_title_text_transform'           => '',
	'typography_sidebar_title_letter_spacing'           => '',
	'typography_sidebar_title_word_spacing'             => '',
	'typography_sidebar_body_font_family'               => '',
	'typography_sidebar_body_font_variant'              => '',
	'typography_sidebar_body_font_size'                 => '',
	'typography_sidebar_body_line_height'               => '',
	'typography_sidebar_body_text_transform'            => '',
	'typography_sidebar_body_letter_spacing'            => '',
	'typography_sidebar_body_word_spacing'              => '',
	'typography_footer_title_font_family'               => '',
	'typography_footer_title_font_variant'              => '',
	'typography_footer_title_font_size'                 => '',
	'typography_footer_title_line_height'               => '',
	'typography_footer_title_text_transform'            => '',
	'typography_footer_title_letter_spacing'            => '',
	'typography_footer_title_word_spacing'              => '',
	'typography_footer_body_font_family'                => '',
	'typography_footer_body_font_variant'               => '',
	'typography_footer_body_font_size'                  => '',
	'typography_footer_body_line_height'                => '',
	'typography_footer_body_text_transform'             => '',
	'typography_footer_body_letter_spacing'             => '',
	'typography_footer_body_word_spacing'               => '',
	'typography_footer_text_font_family'                => '',
	'typography_footer_text_font_variant'               => '',
	'typography_footer_text_font_size'                  => '',
	'typography_footer_text_line_height'                => '',
	'typography_footer_text_text_transform'             => '',
	'typography_footer_text_letter_spacing'             => '',
	'typography_footer_text_word_spacing'               => '',
	//extra font size
	'typography_x_large_font_size'                      => 24,
	'typography_large_font_size'                        => 18,
	'typography_medium_font_size'                       => 16,
	'typography_small_font_size'                        => 14,
	'typography_x_small_font_size'                      => 10,
	'typography_xx_small_font_size'                     => 9,

	'bg_image_global_site'                              => '',
	'title_bar_title_container'                         => '',
	'layout_enable_title_breadcrumb'                    => 0,
	'woocommerce_general_enable_product_flying_cart'    => 1,
	'woocommerce_general_enable_product_zoom'           => 1,
	'woocommerce_general_enable_product_lightbox'       => 1,
	'woocommerce_general_enable_product_gallery_slider' => 1,
	'woocommerce_general_discount_label_text_prefix'    => __( 'Sale -', 'springoo' ),
	'woocommerce_general_discount_label_text_suffix'    => __( '%', 'springoo' ),
	'woocommerce_shop_archive_title-bar'                => 1,
	'woocommerce_shop_archive_title'                    => 1,
	'woocommerce_shop_archive_per_page'                 => 9,
	'woocommerce_shop_archive_layout'                   => 'none',
	'woocommerce_shop_archive_sidebar'                  => 'shop-sidebar',
	'woocommerce_shop_archive_column'                   => 4,
	'woocommerce_shop_archive_sort'                     => 1,
	'woocommerce_shop_archive_result_count'             => 0,
	'woocommerce_shop_archive_product_archive_layout'   => 'layout_one',
	'woocommerce_single_layout'                         => 'none',
	'woocommerce_single_attribute'                      => 'default',
	'woocommerce_single_sidebar'                        => 'default',
	'woocommerce_single_upsells_count'                  => 4,
	'woocommerce_single_upsells_columns'                => 4,
	'woocommerce_single_related_item_count'             => 4,
	'woocommerce_single_related_product_column'         => 4,
	'woocommerce_single_include_image_gallery'          => 1,
	'woocommerce_single_social_share'                   => 1,
	'woocommerce_taxonomy_archive_cat_layout'           => 'right',
	'woocommerce_taxonomy_archive_cat_sidebar'          => 'shop-sidebar',
	'woocommerce_taxonomy_archive_tag_layout'           => 'right',
	'woocommerce_taxonomy_archive_tag_sidebar'          => 'shop-sidebar',

	//new added for product reviews note
	'woocommerce_single_reviews_note_enable'            => 1,
	'woocommerce_single_reviews_note_label'             => __( 'Designed for simplicity and made from high quality materials. Its sleek geometry and material combinations creates.', 'springoo' ),
	'woocommerce_single_reviews_note_content'           => __( 'Simplicity and made from high quality materials, Its sleek geometry and material', 'springoo' ),


	'woocommerce_cart_title-bar'                        => 1,
	'woocommerce_cart_cross_sell_count'                 => 2,
	'woocommerce_cart_cross_sell_column'                => 2,
	'woocommerce_cart_sidebar_layout'                   => 'none',
	'woocommerce_cart_sidebar'                          => 'default',
	'woocommerce_demo_store'                            => 0,
	'woocommerce_demo_store_info'                       => __( 'This is a demo store for testing purposes &emdash; no orders shall be fulfilled.', 'springoo' ),
	'woocommerce_shop_page_display'                     => '',
	'woocommerce_category_archive_display'              => '',
	'woocommerce_default_catalog_orderby'               => 'menu_order',
	'woocommerce_product_catalog_title'                 => 1,
	'woocommerce_product_catalog_layout'                => 'right',
	'woocommerce_product_catalog_sidebar'               => 'shop-sidebar',
	'woocommerce_checkout_sidebar'                      => 'default',
	'woocommerce_checkout_sidebar_layout'               => 'none',
	'woocommerce_checkout_company_field'                => 'required',
	'woocommerce_checkout_address_2_field'              => 'optional',
	'woocommerce_checkout_phone_field'                  => 'required',
	'woocommerce_checkout_highlight_required_fields'    => 1,
	'wp_page_for_privacy_policy'                        => '',
	'woocommerce_terms_page_id'                         => '',
	'woocommerce_checkout_privacy_policy_text'          => __( 'Your personal data will be used to process your order, support your experience throughout this website, and for other purposes described in our [privacy_policy].', 'springoo' ),
	'woocommerce_checkout_terms_and_conditions_checkbox_text' => __( 'I have read and agree to the website [terms]', 'springoo' ),
	'woocommerce_checkout_title-bar'                    => 1,
	'woocommerce_myaccount_title-bar'                   => 1,
	'woocommerce_myaccount_sidebar_layout'              => 'none',
	'woocommerce_myaccount_sidebar'                     => 'shop-sidebar',
	'woocommerce_single_image_width'                    => '600',
	'woocommerce_thumbnail_image_width'                 => '300',
	'woocommerce_thumbnail_cropping'                    => '1:1',

	//Dokan
	'dokan_template_style'                              => 1,
	'dokan_template_store_per_page'                     => 8,
	'dokan_template_store_columns'                      => 4,


	'layout_wpcf7_columns'                              => 'two-column',
	'layout_wpcf7_top_padding'                          => 15,
	'layout_wpcf7_bottom_padding'                       => 15,
	'layout_wpcf7_left_padding'                         => 20,
	'layout_wpcf7_right_padding'                        => 20,
	'layout_wpcf7_border_radius'                        => 0,
	'layout_wpcf7_gap'                                  => 30,
	'layout_wpcf7_textarea_height'                      => 200,
	'layout_wpcf7_btn_position'                         => 'left',
];

$springoo_defaults['choices'] = [
	'layout_global_site'                              => [
		'wide'  => __( 'Wide', 'springoo' ),
		'boxed' => __( 'Boxed', 'springoo' ),
	],
	'layout_global_content_layout'                    => [
		'container'       => __( 'Container', 'springoo' ),
		'container-fluid' => __( 'Container Fluid', 'springoo' ),
	],
	'layout_global_content_grid'                      => $springoo_grid_list,
	'layout_global_sidebar_grid'                      => $springoo_grid_list,

	'preload_animation_type'                          => [
		'none'               => __( 'None', 'springoo' ),
		'bounce'             => __( 'Bounce', 'springoo' ),
		'flash'              => __( 'Flash', 'springoo' ),
		'pulse'              => __( 'Pulse', 'springoo' ),
		'rubberBand'         => __( 'Rubber Band', 'springoo' ),
		'shakeX'             => __( 'Shake X', 'springoo' ),
		'shakeY'             => __( 'Shake Y', 'springoo' ),
		'headShake'          => __( 'Head Shake', 'springoo' ),
		'swing'              => __( 'Swing', 'springoo' ),
		'tada'               => __( 'Ta Da', 'springoo' ),
		'wobble'             => __( 'Wooble', 'springoo' ),
		'jello'              => __( 'Jello', 'springoo' ),
		'heartBeat'          => __( 'Heart Beat', 'springoo' ),
		'backInDown'         => __( 'Back In Down', 'springoo' ),
		'backInLeft'         => __( 'Back In Left', 'springoo' ),
		'backInRight'        => __( 'Back In Right', 'springoo' ),
		'backInUp'           => __( 'Back In Up', 'springoo' ),
		'backOutDown'        => __( 'Back Out Down', 'springoo' ),
		'backOutLeft'        => __( 'Back Out Left', 'springoo' ),
		'backOutRight'       => __( 'Back Out Right', 'springoo' ),
		'backOutUp'          => __( 'Back Out Up', 'springoo' ),
		'bounceIn'           => __( 'Bounce In', 'springoo' ),
		'bounceInDown'       => __( 'Bounce In Down', 'springoo' ),
		'bounceInLeft'       => __( 'Bounce In Left', 'springoo' ),
		'bounceInRight'      => __( 'Bounce In Right', 'springoo' ),
		'bounceInUp'         => __( 'Bounce In Up', 'springoo' ),
		'bounceOut'          => __( 'Bounce Out ', 'springoo' ),
		'bounceOutDown'      => __( 'Bounce Out Down', 'springoo' ),
		'bounceOutLeft'      => __( 'Bounce Out Left', 'springoo' ),
		'bounceOutRight'     => __( 'Bounce Out Right', 'springoo' ),
		'bounceOutUp'        => __( 'Bounce Out Up', 'springoo' ),
		'fadeIn'             => __( 'Fade In', 'springoo' ),
		'fadeInDown'         => __( 'Fade In Down', 'springoo' ),
		'fadeInDownBig'      => __( 'Fade In Down Big', 'springoo' ),
		'fadeInLeft'         => __( 'Fade In Left', 'springoo' ),
		'fadeInLeftBig'      => __( 'Fade In Left Big', 'springoo' ),
		'fadeInRight'        => __( 'Fade In Right', 'springoo' ),
		'fadeInRightBig'     => __( 'Fade In Right Big', 'springoo' ),
		'fadeInUp'           => __( 'Fade In Up', 'springoo' ),
		'fadeInUpBig'        => __( 'Fade In Big', 'springoo' ),
		'fadeInTopLeft'      => __( 'Fade In Top Left', 'springoo' ),
		'fadeInTopRight'     => __( 'Fade In Top Right', 'springoo' ),
		'fadeInBottomLeft'   => __( 'Fade In Bottom Left', 'springoo' ),
		'fadeInBottomRight'  => __( 'Fade In Bottom Right', 'springoo' ),
		'fadeOut'            => __( 'Fade Out', 'springoo' ),
		'fadeOutDown'        => __( 'Fade Out Down', 'springoo' ),
		'fadeOutDownBig'     => __( 'Fade Out Down Big', 'springoo' ),
		'fadeOutLeft'        => __( 'Fade Out Left', 'springoo' ),
		'fadeOutLeftBig'     => __( 'Fade Out Left Big', 'springoo' ),
		'fadeOutRight'       => __( 'Fade Out Right', 'springoo' ),
		'fadeOutRightBig'    => __( 'Fade Out Right Big', 'springoo' ),
		'fadeOutUp'          => __( 'Fade Out Up', 'springoo' ),
		'fadeOutUpBig'       => __( 'Fade Out Big', 'springoo' ),
		'fadeOutTopLeft'     => __( 'Fade Out Top Left', 'springoo' ),
		'fadeOutTopRight'    => __( 'Fade Out Top Right', 'springoo' ),
		'fadeOutBottomRight' => __( 'Fade Out Bottom Right', 'springoo' ),
		'fadeOutBottomLeft'  => __( 'Fade Out Bottom Left', 'springoo' ),
		'Flippers'           => __( 'Flippers', 'springoo' ),
		'flip'               => __( 'Flip', 'springoo' ),
		'flipInX'            => __( 'Flip In X', 'springoo' ),
		'flipInY'            => __( 'Flip In Y', 'springoo' ),
		'flipOutX'           => __( 'Flip Out X', 'springoo' ),
		'flipOutY'           => __( 'Flip Out Y', 'springoo' ),
		'Lightspeed'         => __( 'Light Speed', 'springoo' ),
		'lightSpeedInRight'  => __( 'Light Speed In Right', 'springoo' ),
		'lightSpeedInLeft'   => __( 'Light Speed In Left', 'springoo' ),
		'lightSpeedOutRight' => __( 'Light Speed Out Right', 'springoo' ),
		'lightSpeedOutLeft'  => __( 'Light Speed Out Left', 'springoo' ),
		'rotateIn'           => __( 'Rotate In', 'springoo' ),
		'rotateInDownLeft'   => __( 'Rotate In Down Left', 'springoo' ),
		'rotateInDownRight'  => __( 'Rotate In Down Right', 'springoo' ),
		'rotateInUpLeft'     => __( 'Rotate In Up Left', 'springoo' ),
		'rotateInUpRight'    => __( 'Rotate In Up Right', 'springoo' ),
		'Rotating'           => __( 'Rotating', 'springoo' ),
		'rotateOut'          => __( 'Rotate Out', 'springoo' ),
		'rotateOutDownLeft'  => __( 'Rotate Out Down Left', 'springoo' ),
		'rotateOutDownRight' => __( 'Rotate Out Down Right', 'springoo' ),
		'rotateOutUpLeft'    => __( 'Rotate Out Up Left', 'springoo' ),
		'rotateOutUpRight'   => __( 'Rotate Out Up Right', 'springoo' ),
		'Specials'           => __( 'Specials', 'springoo' ),
		'hinge'              => __( 'Hinge', 'springoo' ),
		'jackInTheBox'       => __( 'Jack In The Box', 'springoo' ),
		'rollIn'             => __( 'Roll In', 'springoo' ),
		'rollOut'            => __( 'Roll Out', 'springoo' ),
		'zoomIn'             => __( 'Zoom In', 'springoo' ),
		'zoomInDown'         => __( 'Zoom In Down', 'springoo' ),
		'zoomInLeft'         => __( 'Zoom In Left', 'springoo' ),
		'zoomInRight'        => __( 'Zoom In Right', 'springoo' ),
		'zoomInUp'           => __( 'Zoom In Up', 'springoo' ),
		'zoomOut'            => __( 'Zoom Out', 'springoo' ),
		'zoomOutDown'        => __( 'Zoom Out Down', 'springoo' ),
		'zoomOutLeft'        => __( 'Zoom Out left', 'springoo' ),
		'zoomOutRight'       => __( 'Zoom Out Right', 'springoo' ),
		'zoomOutUp'          => __( 'Zoom Out Up', 'springoo' ),
		'slideInDown'        => __( 'Slide In Down', 'springoo' ),
		'slideInLeft'        => __( 'Slide In Left', 'springoo' ),
		'slideInRight'       => __( 'Slide In Right', 'springoo' ),
		'slideInUp'          => __( 'Slide In Up', 'springoo' ),
		'slideOutDown'       => __( 'Slide Out Down', 'springoo' ),
		'slideOutLeft'       => __( 'Slide Out Left', 'springoo' ),
		'slideOutRight'      => __( 'Slide Out Right', 'springoo' ),
		'slideOutUp'         => __( 'Slide Out Up', 'springoo' ),
	],
	'preload_animation_speed'                         => [
		'slower' => __( 'Slower', 'springoo' ),
		'slow'   => __( 'Slow', 'springoo' ),
		'fast'   => __( 'Fast', 'springoo' ),
		'faster' => __( 'Faster', 'springoo' ),
	],
	'preload_text_size'                               => [
		'min'  => 0,
		'max'  => 200,
		'step' => 1,
	],
	'preload_img_size'                                => [
		'min'  => 20,
		'max'  => 400,
		'step' => 1,
	],

	'layout_blog_sidebar'                             => $springoo_sidebar_pos,
	'layout_archive_sidebar'                          => $springoo_sidebar_pos,
	'layout_search_sidebar'                           => $springoo_sidebar_pos,
	'layout_post_sidebar'                             => $springoo_sidebar_pos,
	'layout_page_sidebar'                             => $springoo_sidebar_pos,
	'layout_blog_style'                               => $springoo_blog_style,
	'layout_archive_style'                            => $springoo_blog_style,
	'layout_search_style'                             => $springoo_search_style,
	'layout_blog_title-bar'                           => $springoo_yes_no,
	'layout_archive_title-bar'                        => $springoo_yes_no,
	'layout_search_title-bar'                         => $springoo_yes_no,
	'layout_post_title-bar'                           => $springoo_yes_no,
	'layout_post_title'                               => $springoo_yes_no,
	'layout_page_title-bar'                           => $springoo_yes_no,
	'layout_page_title'                               => $springoo_yes_no,
	'layout_post_content_align'                       => $springoo_content_align,
	'layout_page_content_align'                       => $springoo_content_align,
	'layout_related_post_number'                      => [
		'min'  => 0,
		'max'  => 100,
		'step' => 1,
	],
	'layout_related_post_column'                      => [
		'min'  => 1,
		'max'  => 6,
		'step' => 1,
	],
	'layout_header_height'                            => [
		'min'  => 40,
		'max'  => 200,
		'step' => 1,
	],
	'layout_header_menu_height'                       => [
		'min'  => 20,
		'max'  => 200,
		'step' => 1,
	],
	'layout_header_button_top_padding'                => [
		'min'  => 0,
		'max'  => 100,
		'step' => 1,
	],
	'layout_header_button_bottom_padding'             => [
		'min'  => 0,
		'max'  => 100,
		'step' => 1,
	],
	'layout_header_button_left_padding'               => [
		'min'  => 0,
		'max'  => 100,
		'step' => 1,
	],
	'layout_header_button_right_padding'              => [
		'min'  => 0,
		'max'  => 100,
		'step' => 1,
	],
	'layout_header_button_border_radius'              => [
		'min'  => 0,
		'max'  => 100,
		'step' => 1,
	],
	'layout_header_sticky_height'                     => [
		'min'  => 40,
		'max'  => 200,
		'step' => 1,
	],
	'layout_header_menu_mobileshow'                   => [
		'sm' => __( 'Small Device', 'springoo' ),
		'md' => __( 'Medium Device', 'springoo' ),
		'lg' => __( 'Large Device', 'springoo' ),
		'xl' => __( 'Extra Large Device', 'springoo' ),
	],
	'layout_header_mobile_menu_style'                 => [
		'off-canvas-full-mobile-menu'  => __( 'Off-Canvas Full', 'springoo' ),
		'off-canvas-left-mobile-menu'  => __( 'Off-Canvas Left', 'springoo' ),
		'off-canvas-right-mobile-menu' => __( 'Off-Canvas Right', 'springoo' ),
	],
	'layout_header_menu_alignment'                    => [
		'right'  => __( 'Right', 'springoo' ),
		'center' => __( 'Center', 'springoo' ),
		'left'   => __( 'Left', 'springoo' ),
	],
	'layout_header_menu_style'                        => [
		'menu-text'      => __( 'Text Color ', 'springoo' ),
		'menu-heading'   => __( 'Heading Color ', 'springoo' ),
		'menu-primary'   => __( 'Primary Color ', 'springoo' ),
		'menu-secondary' => __( 'Secondary Color ', 'springoo' ),
		'menu-white'     => __( 'White Color', 'springoo' ),
		'menu-custom'    => __( 'Custom Color', 'springoo' ),
	],
	'layout_header_menu_hover_style'                  => [
		'menu-hover-text'      => __( 'Text Color', 'springoo' ),
		'menu-hover-heading'   => __( 'Heading Color', 'springoo' ),
		'menu-hover-primary'   => __( 'Primary Color', 'springoo' ),
		'menu-hover-secondary' => __( 'Secondary Color', 'springoo' ),
		'menu-hover-white'     => __( 'White Color', 'springoo' ),
		'menu-hover-custom'    => __( 'Custom Color', 'springoo' ),
	],
	'layout_header_submenu_alignment'                 => $springoo_content_align,
	'layout_header_submenu_width'                     => [
		'min'  => 200,
		'max'  => 400,
		'step' => 1,
	],
	'layout_header_submenu_top_padding'               => [
		'min'  => 0,
		'max'  => 50,
		'step' => 1,
	],
	'layout_header_submenu_bottom_padding'            => [
		'min'  => 0,
		'max'  => 50,
		'step' => 1,
	],
	'layout_header_submenu_left_padding'              => [
		'min'  => 0,
		'max'  => 50,
		'step' => 1,
	],
	'layout_header_submenu_right_padding'             => [
		'min'  => 0,
		'max'  => 50,
		'step' => 1,
	],
	'layout_header_menu_left_padding'                 => [
		'min'  => 0,
		'max'  => 50,
		'step' => 1,
	],
	'layout_header_menu_right_padding'                => [
		'min'  => 0,
		'max'  => 50,
		'step' => 1,
	],
	'layout_header_mega_menu_bottom_spacing'          => [
		'min'  => 0,
		'max'  => 50,
		'step' => 1,
	],
	'layout_transparent_header_top_margin'            => [
		'min'  => 0,
		'max'  => 50,
		'step' => 1,
	],

	'layout_footer_widget_column'                     => [
		12 => __( '1 Column', 'springoo' ),
		6  => __( '2 Column', 'springoo' ),
		4  => __( '3 Column', 'springoo' ),
		3  => __( '4 Column', 'springoo' ),
	],
	'layout_footer_main_top_padding'                  => [
		'min'  => 0,
		'max'  => 100,
		'step' => 1,
	],
	'layout_footer_main_bottom_padding'               => [
		'min'  => 0,
		'max'  => 100,
		'step' => 1,
	],
	'layout_footer_bottom_top_padding'                => [
		'min'  => 0,
		'max'  => 100,
		'step' => 1,
	],
	'layout_footer_bottom_bottom_padding'             => [
		'min'  => 0,
		'max'  => 100,
		'step' => 1,
	],
	'layout_footer_credits_top_padding'               => [
		'min'  => 0,
		'max'  => 100,
		'step' => 1,
	],
	'layout_footer_credits_bottom_padding'            => [
		'min'  => 0,
		'max'  => 100,
		'step' => 1,
	],
	'typography_options_subsets'                      => [
		'latin'        => __( 'Latin', 'springoo' ),
		'latin-ext'    => __( 'Latin Extended', 'springoo' ),
		'greek'        => __( 'Greek', 'springoo' ),
		'greek-ext'    => __( 'Greek Extended', 'springoo' ),
		'cyrillic'     => __( 'Cyrillic', 'springoo' ),
		'cyrillic-ext' => __( 'Cyrillic Extended', 'springoo' ),
		'vietnamese'   => __( 'Vietnamese', 'springoo' ),
		'arabic'       => __( 'Arabic', 'springoo' ),
		'khmer'        => __( 'Khmer', 'springoo' ),
		'devanagari'   => __( 'Devanagari', 'springoo' ),
	],
	'woocommerce_general_menu_cart'                   => [
		'icon'       => __( 'Icon', 'springoo' ),
		'icon-cart'  => __( 'Icon And Cart Total', 'springoo' ),
		'icon-count' => __( 'Icon And Cart Count', 'springoo' ),
		'disable'    => __( 'Disable', 'springoo' ),
	],
	'woocommerce_shop_archive_title-bar'              => [
		1 => __( 'Yes', 'springoo' ),
		0 => __( 'No', 'springoo' ),
	],
	'woocommerce_shop_archive_layout'                 => [
		'left'  => __( 'Left', 'springoo' ),
		'right' => __( 'Right', 'springoo' ),
		'none'  => __( 'None', 'springoo' ),
	],
	'woocommerce_shop_archive_sidebar'                => $sidebar_list,
	'woocommerce_shop_archive_column'                 => $springoo_grid_list,
	'woocommerce_product_catalog_title-bar'           => [
		1 => __( 'Yes', 'springoo' ),
		0 => __( 'No', 'springoo' ),
	],
	'woocommerce_taxonomy_archive_cat_sidebar'        => $sidebar_list,
	'woocommerce_taxonomy_archive_cat_layout'         => [
		'left'  => __( 'Left', 'springoo' ),
		'right' => __( 'Right', 'springoo' ),
		'none'  => __( 'None', 'springoo' ),
	],
	'woocommerce_taxonomy_archive_tag_sidebar'        => $sidebar_list,
	'woocommerce_taxonomy_archive_tag_layout'         => [
		'left'  => __( 'Left', 'springoo' ),
		'right' => __( 'Right', 'springoo' ),
		'none'  => __( 'None', 'springoo' ),
	],
	'woocommerce_product_catalog_sidebar'             => $sidebar_list,
	'woocommerce_product_catalog_layout'              => [
		'left'  => __( 'Left', 'springoo' ),
		'right' => __( 'Right', 'springoo' ),
		'none'  => __( 'None', 'springoo' ),
	],
	'woocommerce_single_layout'                       => [
		'left'  => __( 'Left', 'springoo' ),
		'right' => __( 'Right', 'springoo' ),
		'none'  => __( 'None', 'springoo' ),
	],
	'woocommerce_single_attribute'                    => [
		'default'  => __( 'Default', 'springoo' ),
		'checkbox' => __( 'Checkbox', 'springoo' ),
	],
	'woocommerce_single_sidebar'                      => $sidebar_list,
	'woocommerce_single_product_gallery_lightbox'     => [
		'disable'              => __( 'Disable', 'springoo' ),
		'theme-lightbox'       => __( 'Theme Lightbox', 'springoo' ),
		'woocommerce-lightbox' => __( 'WooCommerce Lightbox', 'springoo' ),
	],
	'woocommerce_single_upsells_columns'              => $springoo_grid_list,
	'woocommerce_single_related_product_column'       => $springoo_grid_list,
	'woocommerce_shop_archive_product_archive_layout' => [
		'layout_one'   => __( 'Layout One', 'springoo' ),
		'layout_two'   => __( 'Layout Two', 'springoo' ),
		'layout_three' => __( 'Layout Three', 'springoo' ),
	],
	'woocommerce_cart_title-bar'                      => [
		1 => __( 'Yes', 'springoo' ),
		0 => __( 'No', 'springoo' ),
	],
	'woocommerce_general_enable_product_flying_cart'  => [
		1 => __( 'Yes', 'springoo' ),
		0 => __( 'No', 'springoo' ),
	],
	'woocommerce_cart_cross_sell_column'              => $springoo_grid_list,
	'woocommerce_cart_sidebar_layout'                 => [
		'left'  => __( 'Left', 'springoo' ),
		'right' => __( 'Right', 'springoo' ),
		'none'  => __( 'None', 'springoo' ),
	],
	'woocommerce_cart_sidebar'                        => $sidebar_list,
	'woocommerce_checkout_sidebar_layout'             => [
		'left'  => __( 'Left', 'springoo' ),
		'right' => __( 'Right', 'springoo' ),
		'none'  => __( 'None', 'springoo' ),
	],
	'woocommerce_checkout_title-bar'                  => [
		1 => __( 'Yes', 'springoo' ),
		0 => __( 'No', 'springoo' ),
	],
	'woocommerce_myaccount_title-bar'                 => [
		1 => __( 'Yes', 'springoo' ),
		0 => __( 'No', 'springoo' ),
	],
	'woocommerce_myaccount_sidebar_layout'            => [
		'left'  => __( 'Left', 'springoo' ),
		'right' => __( 'Right', 'springoo' ),
		'none'  => __( 'None', 'springoo' ),
	],
	'woocommerce_myaccount_sidebar'                   => $sidebar_list,
	'woocommerce_checkout_sidebar'                    => $sidebar_list,
	'layout_wpcf7_columns'                            => [
		'two-column'    => __( 'Two Column', 'springoo' ),
		'single-column' => __( 'Single Column', 'springoo' ),
	],

	// Dokan Template Option
	'dokan_template_style'                            => [
		1 => __( 'Style One', 'springoo' ),
		2 => __( 'Style Two', 'springoo' ),
		3 => __( 'Style Three', 'springoo' ),
	],

	'dokan_template_store_per_page'                   => [
		'min'  => 0,
		'max'  => 60,
		'step' => 1,
	],

	'dokan_template_store_columns'                    => [
		2 => __( '2 Column', 'springoo' ),
		3 => __( '3 Column', 'springoo' ),
		4 => __( '4 Column', 'springoo' ),
	],

	'layout_wpcf7_top_padding'                        => [
		'min'  => 0,
		'max'  => 200,
		'step' => 1,
	],
	'layout_wpcf7_bottom_padding'                     => [
		'min'  => 0,
		'max'  => 200,
		'step' => 1,
	],
	'layout_wpcf7_left_padding'                       => [
		'min'  => 0,
		'max'  => 200,
		'step' => 1,
	],
	'layout_wpcf7_right_padding'                      => [
		'min'  => 0,
		'max'  => 200,
		'step' => 1,
	],
	'layout_wpcf7_border_radius'                      => [
		'min'  => 0,
		'max'  => 200,
		'step' => 1,
	],
	'layout_wpcf7_textarea_height'                    => [
		'min'  => 40,
		'max'  => 400,
		'step' => 1,
	],
	'layout_wpcf7_gap'                                => [
		'min'  => 0,
		'max'  => 400,
		'step' => 1,
	],
	'layout_wpcf7_btn_position'                       => [
		'left'  => __( 'Left', 'springoo' ),
		'right' => __( 'Right', 'springoo' ),
	],
];
// phpcs:enable
